config/routes.rb
Rails.application.routes.draw do

  # root to: "home#error"

	root to: 'home#index'

	resources :exhaustions, except: [:index] do
		get :pictures
		post :pictures, to: "exhaustions#upload"
    delete :pictures, to: "exhaustions#destroy_image"
		post '/pdf', to: 'exhaustions#pdf_create', as: :pdf_create
	end

	resources :inspections, except: [:index] do
    get :pictures
    post :pictures, to: "inspections#upload"
    delete :pictures, to: "inspections#destroy_image"
  end

	resources :schedulings, except: :show
	resources :clients, except: :show
	resources :users, except: :show
	resources	:account_activations,	only: [:edit, :update]
  resources :password_resets,     only: [:new, :create, :edit, :update]

	get    'report',  to: "report#show"
	post   'report', to: "report#generate"
	get    'resend/activation',  to: "account_activations#request_resend"
	post   'resend/activation', to: "account_activations#resend"
	get 	 'address/:cep',  to: "address#show"
	get    'login', 				to: 'sessions#new'
  post   'login', 				to: 'sessions#create'
  delete 'logout', 				to: 'sessions#destroy'
	post 'schedulings/index', to: 'schedulings#index', as: :search
end

app/models/scheduling.rb
class Scheduling < ActiveRecord::Base
	enum service: [ :vistoria, :limpeza_exaustao, :limpeza_ar_condicionado ]
  belongs_to :client
  belongs_to :parent, class_name: 'Client', foreign_key: :parent_id
  belongs_to :user
  has_one :execution, dependent: :destroy
  validates :service, :parent, :client, :date, :user, presence: true
	default_scope { order date: :desc }
end

app/controllers/schedulings_controller.rb
class SchedulingsController < ApplicationController
  before_action :set_scheduling, only: [:show, :edit, :update, :destroy]
  require 'date'
  # GET /schedulings
  # GET /schedulings.json
  def index
    authorize Scheduling

    if params[:scheduling].nil?
      @schedulings = policy_scope(Scheduling).paginate(:page => params[:page], :per_page => 100)
    else
      search = params[:scheduling][:search] if !params[:scheduling][:search].nil?


      case params[:scheduling][:type]
      when 'client'
        clients_id = Client.where("name LIKE UPPER(?) ", "%#{search.upcase}%").pluck(:id)
        @schedulings = policy_scope(Scheduling).where(client_id: clients_id).paginate(:page => params[:page], :per_page => 100)
      when 'filial'
        filials = Client.where("name LIKE UPPER(?) ", "%#{search.upcase}%").pluck(:id)
        @schedulings = policy_scope(Scheduling).where(client_id: clients_id).paginate(:page => params[:page], :per_page => 100)
      when 'data'
        search = DateTime.parse(search)
        search = search.strftime('%Y-%m-%d')

        @schedulings = policy_scope(Scheduling.where("DATE(date) = ?","#{search}")).paginate(:page => params[:page], :per_page => 100)
      end


    end
  end

  # GET /schedulings/new
  def new
    @scheduling = Scheduling.new
    authorize @scheduling
  end

  # GET /schedulings/1/edit
  def edit
  end

  # POST /schedulings
  # POST /schedulings.json
  def create
    @scheduling = Scheduling.new(scheduling_params)
    authorize @scheduling
    respond_to do |format|
      if @scheduling.save
        format.html { redirect_to schedulings_url, notice: 'Agendamento criado com sucesso.' }
        format.json { render :show, status: :created, location: @scheduling }
      else
        format.html { render :new }
        format.json { render json: @scheduling.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedulings/1
  # PATCH/PUT /schedulings/1.json
  def update
    respond_to do |format|
      if @scheduling.update(scheduling_params)
        format.html { redirect_to schedulings_url, notice: 'Agendamento atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @scheduling }
      else
        format.html { render :edit }
        format.json { render json: @scheduling.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedulings/1
  # DELETE /schedulings/1.json
  def destroy
    @scheduling.destroy
    respond_to do |format|
      format.html { redirect_to schedulings_url, notice: 'Agendamento removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scheduling
      @scheduling = Scheduling.find(params[:id])
      authorize @scheduling
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scheduling_params
      params.require(:scheduling).permit(:service, :date, :parent_id, :client_id, :user_id, :search)
    end
end

app/views/schedulings/_form.html.erb
<%= form_for @scheduling, html: { class:"form-horizontal" } do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<div class="form-group">
  <%= f.label :service, class: "col-sm-2 control-label required" %>
  <div class="col-sm-10">
    <%= f.select :service, Scheduling.services.keys.map { |w| [t("types.#{w}"), w] }, { include_blank: true }, { class: 'form-control' } %>
  </div>
</div>
<div class="hr-line-dashed"></div>

<div class="form-group">
  <%= f.label :date, class: "col-sm-2 control-label required" %>
  <div class="col-sm-10">
    <div class="input-group date">
      <%= f.text_field :date, class: 'form-control datetimepicker' %>
      <div class="input-group-addon">
        <span class="glyphicon glyphicon-th"></span>
      </div>
    </div>
  </div>
</div>
<div class="hr-line-dashed"></div>

<div class="form-group">
  <%= f.label :parent, class: "col-sm-2 control-label required" %>
  <div class="col-sm-10">
    <%= f.select :parent_id, Client.where(parent_id: nil).order(:name).pluck(:name, :id), { include_blank: true }, { class: 'form-control' } %>
  </div>
</div>
<div class="hr-line-dashed"></div>

<div class="form-group">
  <%= f.label :client, class: "col-sm-2 control-label required" %>
  <div class="col-sm-10">
    <%= f.grouped_collection_select :client_id, Client.where(parent_id: nil).order(:name), :child, :name, :id, :name, { include_blank: true }, { class: 'form-control' } %>
  </div>
</div>
<div class="hr-line-dashed"></div>

<div class="form-group">
  <%= f.label :user, class: "col-sm-2 control-label required" %>
  <div class="col-sm-10">
    <%= f.select :user_id, User.all.pluck(:name, :id), { include_blank: true }, { class: 'form-control' } %>
  </div>
</div>
<div class="hr-line-dashed"></div>

<div class="form-group">
  <div class="col-sm-8 col-sm-offset-2">
    <%= f.submit class: "btn btn-success", data: { disable_with: "Processando..." } %>
  </div>
</div>
<% end %>

app/views/schedulings/edit.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="ibox float-e-margins">
			<div class="ibox-title">
				<h5>Editar Agendamento</h5>
			</div>
			<div class="ibox-content">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/schedulings/index.html.erb
<div class="row">
  <div class="col-md-12" id="list">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>
          <%= link_to new_scheduling_path do %>
          <i class="fa fa-plus"></i>
          Novo agendamento
          <% end %>
        </h5>
        <div class="lado-direito" >

        </div>

      </div>
      <div class="ibox-content">
        <div class="row">
          <div class="col-sm-6"></div>
          <div class="col-sm-6">
            <div id="DataTables_Table_0_filter" class="dataTables_filter">
              <form class="form-horizontal" action="/schedulings/index" method="post">
                <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
                <div class="form-group">
                  <input type="radio" name="scheduling[type]" value="client" checked>Cliente/Filial
                  <input type="radio" name="scheduling[type]" value="data">Data
                  <input class="" type="text" name="scheduling[search]" value="">
                  <button type="send" name="button">Buscar</button>
                </div>
              </form>
            </div>
          </div>
        </div>

        <table class="table table-stripped">
          <thead>
            <tr>
              <th data-hide="phone">Serviço</th>
              <th>Data</th>
              <th data-hide="phone,tablet">Cliente</th>
              <th data-hide="phone,tablet">Filial</th>
              <th data-hide="phone,tablet">Técnico</th>
              <th data-hide="phone,tablet" data-sort-ignore="true"></th>
            </tr>
          </thead>
          <tbody>
            <% @schedulings.each do |scheduling| %>
            <tr>
              <td><%= t("types.#{scheduling.service}") %></td>
              <td><%= scheduling.date %></td>
              <td>
              <%= if scheduling.parent then scheduling.parent.name else "---" end %>
              </td>
              <td><%= scheduling.client.name %></td>
              <td><%= scheduling.user.name %></td>
              <td>
                <%= link_to '', scheduling, method: 'delete', data: { confirm: 'Tem certeza?' }, class:'actions pull-right fa fa-trash text-danger' %>
                <%= link_to '', edit_scheduling_path(scheduling), class:'actions pull-right fa fa-edit text-navy' %>
                <% if scheduling.limpeza_exaustao? || scheduling.limpeza_ar_condicionado?  %>
                  <% if scheduling.execution  %>
                    <%= link_to '', scheduling.execution.actable, class:'actions pull-right fa fa-check text-success' %>
                  <% else %>
                    <%= link_to '', new_exhaustion_path(scheduling_id: scheduling.id), class:'actions pull-right fa fa-calendar text-warning' %>
                  <% end %>
                <% end %>
                <% if scheduling.vistoria?  %>
                  <% if scheduling.execution  %>
                    <%= link_to '', scheduling.execution.actable, class:'actions pull-right fa fa-check text-success' %>
                  <% else %>
                    <%= link_to '', new_inspection_path(scheduling_id: scheduling.id), class:'actions pull-right fa fa-calendar text-warning' %>
                  <% end %>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      <ul class="pagination">
        <%= will_paginate @schedulings, renderer: BootstrapPagination::Rails, params: params.to_unsafe_h %>
      </ul>
      </div>
    </div>
  </div>
</div>

app/views/schedulings/new.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="ibox float-e-margins">
			<div class="ibox-title">
				<h5>Novo Agendamento</h5>
			</div>
			<div class="ibox-content">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>