config/routes.rb
Rails.application.routes.draw do

  # root to: "home#error"

	root to: 'home#index'

	resources :exhaustions, except: [:index] do
		get :pictures
		post :pictures, to: "exhaustions#upload"
    delete :pictures, to: "exhaustions#destroy_image"
		post '/pdf', to: 'exhaustions#pdf_create', as: :pdf_create
	end

	resources :inspections, except: [:index] do
    get :pictures
    post :pictures, to: "inspections#upload"
    delete :pictures, to: "inspections#destroy_image"
  end

	resources :schedulings, except: :show
	resources :clients, except: :show
	resources :users, except: :show
	resources	:account_activations,	only: [:edit, :update]
  resources :password_resets,     only: [:new, :create, :edit, :update]

	get    'report',  to: "report#show"
	post   'report', to: "report#generate"
	get    'resend/activation',  to: "account_activations#request_resend"
	post   'resend/activation', to: "account_activations#resend"
	get 	 'address/:cep',  to: "address#show"
	get    'login', 				to: 'sessions#new'
  post   'login', 				to: 'sessions#create'
  delete 'logout', 				to: 'sessions#destroy'
	post 'schedulings/index', to: 'schedulings#index', as: :search
end

app/models/inspection.rb
class Inspection < ActiveRecord::Base
	acts_as :execution
  #has_many :pictures, through: :execution, dependent: :destroy
end

app/controllers/inspections_controller.rb
# encoding: UTF-8
class InspectionsController < ApplicationController
  before_action :set_inspection, only: [:show, :edit, :update, :destroy]

  # GET /inspections/new
	def new
		@inspection = Inspection.new(scheduling_id: params[:scheduling_id])
    authorize @inspection
	end

  # GET /inspections/1
	def show
    respond_to do |format|
      format.html
      format.pdf do
        pdf = InspectionPdf.new(@inspection, view_context)
          send_data pdf.render,
          filename: "vistoria_#{@inspection.id}.pdf",
          type: "application/pdf",
          disposition: "inline"
      end
    end
	end

  # POST /inspections
  # POST /inspections.json
	def create
		@inspection = Inspection.new(inspection_params)
    authorize @inspection
		respond_to do |format|
			if @inspection.save
				format.html { redirect_to @inspection, notice: 'Vistoria realizada com sucesso.' }
				format.json { render json: @inspection, status: :created, location: @inspection }
			else
				format.html { render action: "new" }
				format.json { render json: @inspection.errors, status: :unprocessable_entity }
			end
		end
	end

  # GET /inspections/1/edit
  def edit
  end

  # PATCH/PUT /inspections/1
  # PATCH/PUT /inspections/1.json
  def update
    respond_to do |format|
      if @inspection.update(inspection_params)
        format.html { redirect_to @inspection, notice: 'Vistoria atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inspections/1
  # DELETE /inspections/1.json
  def destroy
    @inspection.destroy
    respond_to do |format|
      format.html { redirect_to schedulings_path, notice: 'Vistoria removida com sucesso.' }
      format.json { head :no_content }
    end
  end

  # GET /inspections/1/pictures
  def pictures
     @inspection = Inspection.find(params[:inspection_id])
     authorize @inspection
  end

  # POST /inspections/1/pictures
  def upload
    inspection = Inspection.find(params[:inspection_id])
    authorize inspection
    @picture = Picture.new(picture_params)
    @picture.execution = inspection.execution
    @picture.image = params[:file]
    @picture.flag = params[:flag]
    @picture.save!
    render json: @picture
  end

   # DELETE /inspections/1/picture
  def destroy_image
    @inspection = Inspection.find(params[:inspection_id])
    authorize @inspection
    @picture = Picture.find(params[:picture_id])
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to @inspection, notice: 'Imagem removida com sucesso.' }
      format.json { head :no_content }
    end
  end

private

  def set_inspection
    @inspection = Inspection.find(params[:id])
    authorize @inspection
  end

	def inspection_params
		params.require(:inspection).permit(:manager, :scheduling_id,
			:hoods_state, :hoods_clean, :flame_trap, :flame_damper, :flame_system,
			:fog, :risk, :exhaustion, :window, :ducts, :observation)
	end

  def picture_params
    params.require(:picture).permit(:inspection_id, :picture, :flag)
  end
end

app/views/inspections/_form.html.erb
<%= form_for @inspection, html: { class:"form-horizontal"} do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="row">
	<div class="form-group">
		<%= f.label :manager, :class => 'col-sm-2  control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :manager, class: 'form-control'  %>
		</div>
	</div>
	<div class="hr-line-dashed"></div>
	<div class="form-group">
		<%= f.label :observation, :class => 'col-sm-2  control-label' %>
		<div class="col-sm-10">
			<%= f.text_area :observation, class: 'form-control'  %>
		</div>
	</div>
	<div class="hr-line-dashed"></div>
</div>
<div class="row">
	<div class="col-sm-6">
		<div class="form-group">
			<%= f.label :hoods_state, :class => 'col-sm-10  control-label' %>
			<div class="col-sm-2">
				<%= f.check_box :hoods_state, class: 'form-control js-switch'  %>
			</div>
		</div>

		<div class="hr-line-dashed"></div>
		<div class="form-group">
			<%= f.label :hoods_clean, :class => 'col-sm-10  control-label' %>
			<div class="col-sm-2">
				<%= f.check_box :hoods_clean, class: 'form-control js-switch'  %>
			</div>
		</div>
		<div class="hr-line-dashed"></div>

		<div class="form-group">
			<%= f.label :flame_trap, :class => 'col-sm-10  control-label' %>
			<div class="col-sm-2">
				<%= f.check_box :flame_trap, class: 'form-control js-switch'  %>
			</div>
		</div>
		<div class="hr-line-dashed"></div>

		<div class="form-group">
			<%= f.label :flame_damper, :class => 'col-sm-10  control-label' %>
			<div class="col-sm-2">
				<%= f.check_box :flame_damper, class: 'form-control js-switch'  %>
			</div>
		</div>
		<div class="hr-line-dashed"></div>

		<div class="form-group">
			<%= f.label :flame_system, :class => 'col-sm-10  control-label' %>
			<div class="col-sm-2">
				<%= f.check_box :flame_system, class: 'form-control js-switch'  %>
			</div>
		</div>
		<div class="hr-line-dashed"></div>

	</div>
<div class="col-sm-6">
		<div class="form-group">
			<%= f.label :fog, :class => 'col-sm-10  control-label' %>
			<div class="col-sm-2">
				<%= f.check_box :fog, class: 'form-control js-switch'  %>
			</div>
		</div>

		<div class="hr-line-dashed"></div>
		<div class="form-group">
			<%= f.label :risk, :class => 'col-sm-10  control-label' %>
			<div class="col-sm-2">
				<%= f.check_box :risk, class: 'form-control js-switch'  %>
			</div>
		</div>

		<div class="hr-line-dashed"></div>
		<div class="form-group">
			<%= f.label :exhaustion, :class => 'col-sm-10  control-label' %>
			<div class="col-sm-2">
				<%= f.check_box :exhaustion, class: 'form-control js-switch'  %>
			</div>
		</div>

		<div class="hr-line-dashed"></div>
		<div class="form-group">
			<%= f.label :window, :class => 'col-sm-10  control-label' %>
			<div class="col-sm-2">
				<%= f.check_box :window, class: 'form-control js-switch'  %>
			</div>
		</div>
		<div class="hr-line-dashed"></div>

		<div class="form-group">
			<%= f.label :ducts, :class => 'col-sm-10  control-label' %>
			<div class="col-sm-2">
				<%= f.check_box :ducts, class: 'form-control js-switch'  %>
			</div>
		</div>
		<div class="hr-line-dashed"></div>
	</div>
</div>

<%= f.hidden_field :scheduling_id, value: @inspection.scheduling.id %>

<div class="form-group">
	<div class="col-sm-8 col-sm-offset-2">
		<%= f.submit class: "btn btn-success", data: { disable_with: "Processando..." }, id: 'submit-exa' %>
	</div>
</div>
<% end %>

app/views/inspections/edit.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="ibox float-e-margins">
			<div class="ibox-title">
				<h5>Editar Vistoria</h5>
			</div>
			<div class="ibox-content">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/inspections/new.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="ibox float-e-margins">
			<div class="ibox-title">
				<h5>Vistoria</h5>
			</div>
			<div class="ibox-content">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/inspections/pictures.html.erb
<div class="row">
	<div class="col-lg-12">

		<div class="ibox product-detail">
			<div class="ibox-content">

				<div class="row">
					<div class="col-md-4">
						<h2 class="font-bold m-b-xs">
							<%= @inspection.scheduling.parent.name if @inspection.scheduling.parent %>
						</h2>
						<div class="m-t-md">
							<h2 class="product-main-price">
								<%= @inspection.scheduling.client.name %>
							</h2>
						</div>
						<hr>
						<h4>Inspeção</h4>

						<div class="small text-muted">
						</div>
						<dl class="small m-t-md">
							<dt>Gerente atendimento</dt>
							<dd><%= @inspection.manager %></dd>
						</dl>
						<hr>

						<div>
							<div>
								<%= link_to "Voltar", :back, class: "btn btn-default btn-sm" %>
							</div>
						</div>
					</div>
					<div class="col-md-8">
						<h3>Antes:</h3>
						<%= form_for :picture, url: url_for(action: :upload, params: { flag: Picture.flags.keys.first}), :html => {id: 'picture-dropzone', class: :dropzone, multipart: true} do |f| %>
							<div class="dz-message" data-dz-message><span>Clique ou solte arquivos para fazer o upload das fotos antes.</span></div>
							<%= f.hidden_field :image, name: 'picture[image]' %>
						<% end %>
						<div class="hr-line-dashed"></div>
						<h3>Depois:</h3>
						<%= form_for :picture, url: url_for(action: :upload, params: { flag: Picture.flags.keys.second}), :html => {id: 'picture-dropzone', class: :dropzone, multipart: true} do |f| %>
							<div class="dz-message" data-dz-message><span>Clique ou solte arquivos para fazer o upload das fotos depois.</span></div>
							<%= f.hidden_field :image, name: 'picture[image]' %>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/inspections/show.html.erb
<div class="row">
	<div class="col-lg-12">
		<div class="ibox product-detail">
			<div class="ibox-content">

				<div class="row">
					<div class="col-md-4">
						<h2 class="font-bold m-b-xs">
							<%= @inspection.scheduling.parent.name if @inspection.scheduling.parent %>
						</h2>
						<div class="m-t-md">
							<h2 class="product-main-price">
								<%= @inspection.scheduling.client.name %>
							</h2>
						</div>
						<hr>
						<h4>Vistoria</h4>
						<div class="small text-muted">
						</div>
						<dl class="small m-t-md">
							<dt>Gerente atendimento</dt>
							<dd><%= @inspection.manager %></dd>
						</dl>
						<dl class="small m-t-md">
							<dt>Observação</dt>
							<dd><%= @inspection.observation %></dd>
						</dl>
						<hr>
						<div>
							<div>
								<%= link_to "Editar", edit_inspection_path(@inspection), class: "btn btn-primary btn-sm fa fa-edit" %>
								<%= link_to "Adicionar fotos", inspection_pictures_path(@inspection), class: "btn btn-primary btn-sm fa fa-photo" %>
								<%= link_to "", inspection_path(@inspection, format: :pdf), class: "btn btn-success btn-sm fa fa-print" %>
								<%= link_to "", @inspection, method: :delete, class: "btn btn-danger btn-sm fa fa-trash", data: {confirm: 'Tem certeza?'} %>
							</div>
						</div>
					</div>
					<div class="col-md-8">
					<div class="row">
					<div class="col-md-12">
						<h2>Antes:</h2>
						<ul class="rig columns-4">
							<% @inspection.pictures.before.each do |picture| %>
							<li>
								<%= image_tag picture.image.url %>
								<%= link_to "", inspection_pictures_path(@inspection, picture_id: picture.id), method: :delete, class: "pull-left btn btn-danger btn-circle btn-sm fa fa-trash", data: {confirm: 'Tem certeza?'} %>
								<%= link_to "", picture.image.url, class: "btn btn-success btn-circle btn-sm fa fa-eye pull-left", data: {lightbox: true } %>
							</li>
							<% end %>
						</ul>
					</div>
					<div class="col-md-12">
						<h2>Depois:</h2>
						<ul class="rig columns-4">
							<% @inspection.pictures.after.each do |picture| %>
							<li>
								<%= image_tag picture.image.url %>
								<%= link_to "", inspection_pictures_path(@inspection, picture_id: picture.id), method: :delete, class: "pull-left btn btn-danger btn-circle btn-sm fa fa-trash", data: {confirm: 'Tem certeza?'} %>
								<%= link_to "", picture.image.url, class: "btn btn-success btn-circle btn-sm fa fa-eye pull-left", data: {lightbox: true } %>
							</li>
							<% end %>
						</ul>
					</div>
					</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>