config/routes.rb
Rails.application.routes.draw do

  # root to: "home#error"

	root to: 'home#index'

	resources :exhaustions, except: [:index] do
		get :pictures
		post :pictures, to: "exhaustions#upload"
    delete :pictures, to: "exhaustions#destroy_image"
		post '/pdf', to: 'exhaustions#pdf_create', as: :pdf_create
	end

	resources :inspections, except: [:index] do
    get :pictures
    post :pictures, to: "inspections#upload"
    delete :pictures, to: "inspections#destroy_image"
  end

	resources :schedulings, except: :show
	resources :clients, except: :show
	resources :users, except: :show
	resources	:account_activations,	only: [:edit, :update]
  resources :password_resets,     only: [:new, :create, :edit, :update]

	get    'report',  to: "report#show"
	post   'report', to: "report#generate"
	get    'resend/activation',  to: "account_activations#request_resend"
	post   'resend/activation', to: "account_activations#resend"
	get 	 'address/:cep',  to: "address#show"
	get    'login', 				to: 'sessions#new'
  post   'login', 				to: 'sessions#create'
  delete 'logout', 				to: 'sessions#destroy'
	post 'schedulings/index', to: 'schedulings#index', as: :search
end

app/views/layouts/_footer.html.erb
<div class="footer">
		<div>
l				<strong>Todos os direitos reservados</strong> Consulltec &copy; 2015
		</div>
</div>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom white-bg">
    <nav class="navbar navbar-static-top" role="navigation">
        <div class="navbar-header">
            <button aria-controls="navbar" aria-expanded="false" data-target="#navbar"
                data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                <i class="fa fa-reorder"></i>
            </button>
            <%= link_to 'Consulltec', root_path, class: 'navbar-brand' %>
        </div>
        <div class="navbar-collapse collapse" id="navbar">
            <ul class="nav navbar-nav">
                <!-- <li class="<%= is_current_page? root_path %>">
                    <%# link_to 'Início', root_path %>
                </li> -->
                <% if current_user.administrator? or current_user.moderator? %>
                    <li class="<%= is_current_page? users_path %>">
                        <%= link_to 'Usuários', users_path %>
                    </li>
                    <li class="<%= is_current_page? clients_path %>">
                        <%= link_to 'Clientes', clients_path %>
                    </li>
                <% end %>
                <li class="<%= is_current_page? schedulings_path %>">
                    <%= link_to 'Agendamentos', schedulings_path %>
                </li>
                <li class="<%= is_current_page? report_path %>">
                    <%= link_to 'Relatório Gerencial', report_path %>
                </li>
                <!-- <li class="dropdown <%= is_current_page? users_path, clients_path, schedulings_path %>">
                    <a aria-expanded="false" role="button" href="#" class="dropdown-toggle"
                        data-toggle="dropdown"> Menu<span class="caret"></span></a>
                    <ul role="menu" class="dropdown-menu">

                    </ul>
                </li> -->
            </ul>
            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <%= link_to "Perfil", edit_user_path(current_user), class: "fa fa-user" %>
                </li>
                <li>
                    <%= link_to "Sair", logout_path, method: :delete, class: "fa fa-sign-out" %>
                </li>
            </ul>
        </div>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consulltec</title>

    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

</head>
<body class="top-navigation">
    <div id="wrapper">
        <div id="page-wrapper" class="gray-bg">

            <%= render 'layouts/topnavbar' %>

            <div class="wrapper wrapper-content">
                <div class="container">
                    <%= render 'shared/messages' %>
                    <%= yield %>
                </div>
            </div>

            <%= debug(params) if Rails.env.development? %>
            <%= render 'layouts/footer' %>

        </div>
    </div>
</body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consulltec</title>

    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

</head>
<body class="gray-bg">
    <%= render 'shared/messages' %>
    <%= yield %>
</body>
</html>