config/routes.rb
Rails.application.routes.draw do

  # root to: "home#error"

	root to: 'home#index'

	resources :exhaustions, except: [:index] do
		get :pictures
		post :pictures, to: "exhaustions#upload"
    delete :pictures, to: "exhaustions#destroy_image"
		post '/pdf', to: 'exhaustions#pdf_create', as: :pdf_create
	end

	resources :inspections, except: [:index] do
    get :pictures
    post :pictures, to: "inspections#upload"
    delete :pictures, to: "inspections#destroy_image"
  end

	resources :schedulings, except: :show
	resources :clients, except: :show
	resources :users, except: :show
	resources	:account_activations,	only: [:edit, :update]
  resources :password_resets,     only: [:new, :create, :edit, :update]

	get    'report',  to: "report#show"
	post   'report', to: "report#generate"
	get    'resend/activation',  to: "account_activations#request_resend"
	post   'resend/activation', to: "account_activations#resend"
	get 	 'address/:cep',  to: "address#show"
	get    'login', 				to: 'sessions#new'
  post   'login', 				to: 'sessions#create'
  delete 'logout', 				to: 'sessions#destroy'
	post 'schedulings/index', to: 'schedulings#index', as: :search
end

app/models/exhaustion.rb
class Exhaustion < ActiveRecord::Base
	acts_as :execution
	# has_many :pictures, through: :execution, dependent: :destroy
end

app/controllers/exhaustions_controller.rb
# encoding: UTF-8
class ExhaustionsController < ApplicationController
  before_action :set_exhaustion, only: [:show, :edit, :update, :destroy]

  # GET /exhaustions/new
  def new
    @exhaustion = Exhaustion.new(scheduling_id: params[:scheduling_id])
    authorize @exhaustion
  end

  # GET /exhaustions/1
  def show

    respond_to do |format|
      format.html
      # format.pdf do
      #
      # end
    end
  end

  def pdf_create
      @exhaustion = Exhaustion.find(params[:exhaustion_id])
      authorize @exhaustion

      pdf = ExhaustionPdf.new(@exhaustion, params[:enterprise], view_context)
      send_data pdf.render,
      filename: "exaustao_#{@exhaustion.id}.pdf",
      type: "application/pdf",
      disposition: "inline"
  end

  # POST /exhaustions
  # POST /exhaustions.json
  def create
    @exhaustion = Exhaustion.new(exhaustion_params)
    authorize @exhaustion
    respond_to do |format|
     if @exhaustion.save
      format.html { redirect_to @exhaustion, notice: 'Exaustão realizada com sucesso.' }
      format.json { render json: @exhaustion, status: :created, location: @exhaustion }
    else
      format.html { render action: "new" }
      format.json { render json: @exhaustion.errors, status: :unprocessable_entity }
    end
  end
end

  # GET /exhaustions/1/edit
  def edit
  end

  # PATCH/PUT /exhaustions/1
  # PATCH/PUT /exhaustions/1.json
  def update
    respond_to do |format|
      if @exhaustion.update(exhaustion_params)
        format.html { redirect_to @exhaustion, notice: 'Exaustão atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @exhaustion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exhaustions/1
  # DELETE /exhaustions/1.json
  def destroy
    @exhaustion.destroy
    respond_to do |format|
      format.html { redirect_to schedulings_path, notice: 'Exaustão removida com sucesso.' }
      format.json { head :no_content }
    end
  end

  # GET /exhaustions/1/pictures
  def pictures
     @exhaustion = Exhaustion.find(params[:exhaustion_id])
     authorize @exhaustion
  end

  # POST /exhaustions/1/pictures
  def upload
    exhaustion = Exhaustion.find(params[:exhaustion_id])
    authorize exhaustion
    @picture = Picture.new(picture_params)
    @picture.execution = exhaustion.execution
    @picture.image = params[:file]
    @picture.flag = params[:flag]
    @picture.save!
    render json: @picture
  end

   # DELETE /exhaustions/1/picture
  def destroy_image
    @exhaustion = Exhaustion.find(params[:exhaustion_id])
    authorize @exhaustion
    @picture = Picture.find(params[:picture_id])
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to @exhaustion, notice: 'Imagem removida com sucesso.' }
      format.json { head :no_content }
    end
  end

  private

  def set_exhaustion
    @exhaustion = Exhaustion.find(params[:id])
    authorize @exhaustion
  end

  def exhaustion_params
    params.require(:exhaustion).permit(:manager, :scheduling_id, :observation)
  end

  def picture_params
    params.require(:picture).permit(:exhaustion_id, :picture, :flag)
  end
end

app/views/exhaustions/_form.html.erb
<%= form_for @exhaustion, html: { class:"form-horizontal"} do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="form-group">
	<%= f.label :manager, :class => 'col-sm-2  control-label' %>
	<div class="col-sm-10">
		<%= f.text_field :manager, class: 'form-control'  %>
	</div>
</div>
<div class="hr-line-dashed"></div>
<div class="form-group">
	<%= f.label :observation, :class => 'col-sm-2  control-label' %>
	<div class="col-sm-10">
		<%= f.text_area :observation, class: 'form-control'  %>
	</div>
</div>

<%= f.hidden_field :scheduling_id, value: @exhaustion.scheduling.id %>

<div class="form-group">
	<div class="col-sm-8 col-sm-offset-2">
		<% title = @exhaustion.scheduling.service %>
		<%= f.submit 'Criar '+ (t 'types.'+@exhaustion.scheduling.service ) , class: "btn btn-success", data: { disable_with: "Processando..." }, id: 'submit-exa' %>
	</div>
</div>
<% end %>

app/views/exhaustions/edit.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="ibox float-e-margins">
			<div class="ibox-title">
				<h5>Editar Exaustão</h5>
			</div>
			<div class="ibox-content">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/exhaustions/new.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="ibox float-e-margins">
			<div class="ibox-title">
				<h5><%= t @exhaustion.scheduling.service %></h5>
			</div>
			<div class="ibox-content">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/exhaustions/pictures.html.erb
<div class="row">
	<div class="col-lg-12">

		<div class="ibox product-detail">
			<div class="ibox-content">

				<div class="row">
					<div class="col-md-4">
						<h2 class="font-bold m-b-xs">
							<%= @exhaustion.scheduling.parent.name if @exhaustion.scheduling.parent %>
						</h2>
						<div class="m-t-md">
							<h2 class="product-main-price">
								<%= @exhaustion.scheduling.client.name %>
							</h2>
						</div>
						<hr>
						<h4>Exaustão</h4>

						<div class="small text-muted">
						</div>
						<dl class="small m-t-md">
							<dt>Gerente atendimento</dt>
							<dd><%= @exhaustion.manager %></dd>
						</dl>
						<hr>

						<div>
							<div>
								<%= link_to "Voltar", :back, class: "btn btn-default btn-sm" %>
							</div>
						</div>
					</div>
					<div class="col-md-8">
						<h3>Antes:</h3>
						<%= form_for :picture, url: url_for(action: :upload, params: { flag: Picture.flags.keys.first}), :html => {id: 'picture-dropzone', class: :dropzone, multipart: true} do |f| %>
							<div class="dz-message" data-dz-message><span>Clique ou solte arquivos para fazer o upload das fotos antes.</span></div>
							<%= f.hidden_field :image, name: 'picture[image]' %>
						<% end %>
						<div class="hr-line-dashed"></div>
						<h3>Depois:</h3>
						<%= form_for :picture, url: url_for(action: :upload, params: { flag: Picture.flags.keys.second}), :html => {id: 'picture-dropzone', class: :dropzone, multipart: true} do |f| %>
							<div class="dz-message" data-dz-message><span>Clique ou solte arquivos para fazer o upload das fotos depois.</span></div>
							<%= f.hidden_field :image, name: 'picture[image]' %>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/exhaustions/show.html.erb
<div class="row">
	<div class="col-lg-12">
		<div class="ibox product-detail">
			<div class="ibox-content">

				<div class="row">
					<div class="col-md-4">
						<h2 class="font-bold m-b-xs">
							<%= @exhaustion.scheduling.parent.name if @exhaustion.scheduling.parent %>
						</h2>
						<div class="m-t-md">
							<h2 class="product-main-price">
								<%= @exhaustion.scheduling.client.name %>
							</h2>
						</div>
						<hr>
						<h4><%= t @exhaustion.scheduling.service %></h4>
						<div class="small text-muted">
						</div>
						<dl class="small m-t-md">
							<dt>Gerente atendimento</dt>
							<dd><%= @exhaustion.manager %></dd>
						</dl>
						<dl class="small m-t-md">
							<dt>Observação</dt>
							<dd><%= @exhaustion.observation %></dd>
						</dl>
						<hr>
						<div>
							<div>
								<%= link_to "Editar", edit_exhaustion_path(@exhaustion), class: "btn btn-primary btn-sm fa fa-edit" %>
								<%= link_to "Adicionar fotos", exhaustion_pictures_path(@exhaustion), class: "btn btn-primary btn-sm fa fa-photo" %>
								<%= link_to "", "#exhaustionModal", class: "btn btn-success btn-sm fa fa-print", "data-toggle": "modal", "data-target": "#exhaustionModal" %>
								<%= link_to "", @exhaustion, method: :delete, class: "btn btn-danger btn-sm fa fa-trash", data: {confirm: 'Tem certeza?'} %>
							</div>
						</div>
					</div>
					<div class="col-md-8">
					<div class="row">
						<div class="col-md-12">
							<h2>Antes:</h2>
							<ul class="rig columns-4">
								<% @exhaustion.pictures.before.each do |picture| %>
								<li>
									<%= image_tag picture.image.url %>
									<%= link_to "", exhaustion_pictures_path(@exhaustion, picture_id: picture.id), method: :delete, class: "pull-left btn btn-danger btn-circle btn-sm fa fa-trash", data: {confirm: 'Tem certeza?'} %>
									<%= link_to "", picture.image.url, class: "btn btn-success btn-circle btn-sm fa fa-eye pull-left", data: {lightbox: true } %>
								</li>
								<% end %>
							</ul>
						</div>
						<div class="col-md-12">
							<h2>Depois:</h2>
							<ul class="rig columns-4">
								<% @exhaustion.pictures.after.each do |picture| %>
								<li>
									<%= image_tag picture.image.url %>
									<%= link_to "", exhaustion_pictures_path(@exhaustion, picture_id: picture.id), method: :delete, class: "pull-left btn btn-danger btn-circle btn-sm fa fa-trash", data: {confirm: 'Tem certeza?'} %>
									<%= link_to "", picture.image.url, class: "btn btn-success btn-circle btn-sm fa fa-eye pull-left", data: {lightbox: true } %>
								</li>
								<% end %>
							</ul>
						</div>
					</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Modal -->
		<div class="modal fade" id="exhaustionModal" tabindex="-1" role="dialog" aria-labelledby="Exaustão" aria-hidden="true">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <h5 class="modal-title" id="Exaustão">Escolha a empresa</h5>
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		          <span aria-hidden="true">&times;</span>
		        </button>
		      </div>
		      <div class="modal-body">
						 <%= form_tag exhaustion_pdf_create_path(@exhaustion), class: "form-horizontal" do %>
							 		<div class="control-group">
											<label for="Consulltec">Consulltec</label>
											<%= radio_button_tag 'enterprise', 'consulltec', true %>
							 		</div>
									<div class="control-group">
										<label for="MN">MN</label>
										<%= radio_button_tag 'enterprise', 'mn' %>
							 		</div>
									<div class="control-group">
										<label for="RoboClear">RoboClear - Marco Antonio</label>
										<%= radio_button_tag 'enterprise', 'rb_marco_antonio' %>
							 		</div>
									<div class="control-group">
										<label for="RoboClear">RoboClear - Marco Venicius</label>
										<%= radio_button_tag 'enterprise', 'rb_marco_venicius' %>
							 		</div>
									<div class="control-group">
										<%= submit_tag 'Gerar Documento', class:"btn btn-primary" %>
											<!-- <button type="button" class="btn btn-primary">Gerar Documento</button> -->
									</div>
							<% end %>
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
		      </div>
		    </div>
		  </div>
		</div>

	</div>
</div>